server:
  port: 9002

spring:
  application:
    name: qis-server-gateway
  cloud:
    gateway:
      routes: # 路由可以有多个
        - id: service-email-router # 我们自定义的路由 ID，保持唯一
          #uri: http://127.0.0.1:8096  # 目标服务地址  自动投递微服务（部署多实例）  动态路由：uri配置的应该是一个服务名称，而不应该是一个具体的服务实例的地址
          uri: lb://qis-server-email                                                                    # gateway网关从服务注册中心获取实例信息然后负载后路由
          predicates: # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/email/**
        - id: service-code-router      # 我们自定义的路由 ID，保持唯一
          #uri: http://127.0.0.1:8081       # 目标服务地址
          #http://localhost:9002/resume/openstate/1545132

          #http://127.0.0.1:8081/openstate/1545132
          uri: lb://qis-server-code
          predicates: # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/code/**
        - id: service-user-router-login      # 我们自定义的路由 ID，保持唯一
            uri: lb://qis-server-user
            predicates:
              - Path=/user/login/**
            filters:
              - ignoreLoginGlobalFilter
        - id: service-user-router-login-register
            uri: lb://qis-server-user
            predicates:
              - Path=/user/register/**
            filters:
              - ignoreLoginGlobalFilter
        - id: service-user-router      # 我们自定义的路由 ID，保持唯一
          uri: lb://qis-server-user
          predicates: # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/user/**

redirect:
  url: http://localhost/api/login


max:
  count: 100
  request:
    timeUnit: 60
