server:
  port: 9002

spring:
  application:
    name: qis-server-gateway
  cloud:
    gateway:
      routes: # 路由可以有多个
        - id: service-email-router # 我们自定义的路由 ID，保持唯一
          uri: lb://qis-server-email                                                                    # gateway网关从服务注册中心获取实例信息然后负载后路由
          predicates: # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/api/email/**
          filters:
            - StripPrefix=1
        - id: service-code-router-create     # 我们自定义的路由 ID，保持唯一
          uri: lb://qis-server-code
          predicates: # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/api/code/create/**
          filters:
            - StripPrefix=1
            - name: IgnoreLogin
        - id: service-code-router      # 我们自定义的路由 ID，保持唯一
          uri: lb://qis-server-code
          predicates: # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/api/code/**
          filters:
            - StripPrefix=1
        - id: service-user-router-login      # 我们自定义的路由 ID，保持唯一
          uri: lb://qis-server-user
          predicates:
            - Path=/api/user/login/**
          filters:
            - StripPrefix=1
            - name: IgnoreLogin
        - id: service-user-router-login-register
          uri: lb://qis-server-user
          predicates:
            - Path=/api/user/register/**
          filters:
            - StripPrefix=1
            - name: IgnoreLogin
            - name: RegisterBlackList
        - id: service-user-router      # 我们自定义的路由 ID，保持唯一
          uri: lb://qis-server-user
          predicates: # 断言：路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默 认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/api/user/**
          filters:
            - StripPrefix=1
redirect:
  url: http://www.test.com/static/login.html


max:
  count: 100
  request:
    timeUnit: 60